# -*- coding: utf-8 -*-
"""preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/102mJI1zp-O_zSYiZoha1eSsad_v-wnJG
"""

import pandas as pd
import numpy as np

def preprocess(df):

    X = df.drop(columns=["probabilite_defaut"])
    y = df["probabilite_defaut"]

    X = X.select_dtypes(include=['number'])

    if "classe_risque" in X.columns:
        X = X.drop(columns=["classe_risque"])

    mask = ~y.isna()
    X = X[mask]
    y = y[mask]

    X = X.fillna(0)

    # Feature engineering
    if "score_risque_pays" in X.columns:
        X["mean_risk_country"] = X.groupby("score_risque_pays")["score_risque_pays"].transform("mean")

    if "croissance_pays" in X.columns and "risque_sectoriel" in X.columns:
        X["interaction_sector_macro"] = X["croissance_pays"] * X["risque_sectoriel"]

    return X, y