# -*- coding: utf-8 -*-
"""chat_agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/102mJI1zp-O_zSYiZoha1eSsad_v-wnJG
"""

from openai import OpenAI
client = OpenAI()

def chat_ifc(context, question):

    response = client.chat.completions.create(
        model="gpt-5-mini",
        messages=[
            {"role": "system", "content": "Expert IFC credit risk"},
            {"role": "user", "content": context + "\nQuestion: " + question}
        ]
    )

    return response.choices[0].message.content