# -*- coding: utf-8 -*-
"""financial_agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/102mJI1zp-O_zSYiZoha1eSsad_v-wnJG
"""

from openai import OpenAI
client = OpenAI()

def financial_analysis(expected_loss):

    prompt = f"""
    Tu es analyste financier IFC.

    Expected Loss : {expected_loss}

    Donne :
    - Niveau de perte
    - Soutenabilité
    - Risque financier
    """

    response = client.chat.completions.create(
        model="gpt-5-mini",
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content