# -*- coding: utf-8 -*-
"""strategy_agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/102mJI1zp-O_zSYiZoha1eSsad_v-wnJG
"""

from openai import OpenAI
client = OpenAI()

def strategy_analysis(data):

    prompt = f"""
    Tu es expert IFC développement.

    Données :
    {data}

    Analyse :
    - Impact économique
    - Alignement IFC
    - Risques pays / secteur
    """

    response = client.chat.completions.create(
        model="gpt-5-mini",
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content